export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_THEME_SUCCESS = 'CHANGE_THEME_SUCCESS';
export const CHANGE_THEME_FAIL = 'CHANGE_THEME_FAIL';

export const GET_ALL_ROOM_CHAT = 'GET_ALL_ROOM_CHAT';
export const GET_ALL_ROOM_CHAT_SUCCESS = 'GET_ALL_ROOM_CHAT_SUCCESS';
export const GET_ALL_ROOM_CHAT_FAIL = 'GET_ALL_ROOM_CHAT_FAIL';

export const GET_MESSAGES_IN_ROOM_CHAT = 'GET_MESSAGES_IN_ROOM_CHAT';
export const GET_MESSAGES_IN_ROOM_CHAT_SUCCESS =
  'GET_MESSAGES_IN_ROOM_CHAT_SUCCESS';
export const GET_MESSAGES_IN_ROOM_CHAT_FAIL = 'GET_MESSAGES_IN_ROOM_CHAT_FAIL';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const DELETE_ROOM = 'DELETE_ROOM';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';
